<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:app="http://schemas.android.com/apk/res-auto"
xmlns:tools="http://schemas.android.com/tools"
android:layout_width="match_parent"
android:layout_height="match_parent"
android:background="@drawable/bgg"
tools:context=".MainActivity">
<Button
android:id="@+id/button"
android:layout_width="300dp"
android:layout_height="75dp"
android:layout_marginLeft="50dp"
android:layout_marginTop="500dp"
android:text="Date-Time"

android:backgroundTint="@color/teal_200"
/>
<TextView
android:id="@+id/textview1"
android:layout_width="300dp"
android:layout_height="50dp"
android:text=""
android:textSize="30dp"
android:layout_marginLeft="50dp"
android:layout_marginTop="100dp"
android:textColor="@color/white"
/>
<TextView
android:id="@+id/textview2"
android:layout_width="300dp"
android:layout_height="50dp"
android:text=""
android:textSize="30dp"
android:layout_marginLeft="50dp"
android:layout_marginTop="150dp"
android:textColor="@color/white"
/>
</RelativeLayout>
